### ISSUE TITLE
com.google.appengine.api.datastore.DatastoreFailureException: The thread has been interrupted and the request has timed out

### ISSUE THREAD

**Issue by igors48** [igors48/nmdService#357]
http://javatalks.ru/topics/recent.rss

at nmd.orb.util.TransactionTools.rollbackIfActive(TransactionTools.java:16)
    at nmd.orb.services.ReadsService.getFeedItemsReport(ReadsService.java:148)
    at nmd.orb.http.wrappers.ReadsServiceWrapperImpl.getFeedItemsReport(ReadsServiceWrapperImpl.java:129)
    at nmd.orb.http.servlets.reads.ReadsServletGetRequestHandler.handle(ReadsServletGetRequestHandler.java:62)
    at nmd.orb.http.BaseServlet.createResponseBody(BaseServlet.java:69)
    at nmd.orb.http.BaseServlet.service(BaseServlet.java:41)

**Comment by igors48** [comment]
try without description cleaning
